db:
  image: mysql:latest
  ports:
    - "42333:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: example_db
    MYSQL_USER: root
    MYSQL_PASSWORD: root
  volumes:
    - "./db:/docker-entrypoint-initdb.d"
